membuat sidebar pada folder component
mdayat/edu-manager-pro pull request #5
Opened 2023-12-12 12:49 UTC by Farhan-101st

membagi sidebar (html) dengan meletakannya pada folder component

2023-12-12 12:54 UTC, Farhan-101st commented
1. komponen html sidebar telah diletakan pada folder lib/components
2. tampilan sidebar mulai mendekati sesuai rancangan figma pada project plan
3. proses routing antar page sudah berhasil

kendala:
1. komponen card pada masing-masing menu belum tersedia
2. tampilan logout harapannya dapat diletakan pada menu dashboard
3. proses integrasi dan pengambilan data dari backend belum terlaksana

2023-12-12 13:23 UTC, mdayat requested changes

2023-12-12 13:23 UTC, mdayat commented on src/lib/components/Sidebar.svelte
> +<html lang="en">
Jika membuat komponen svelte, tidak perlu menambahkan tag `html`, `head`, dan `body`. Karena tag-tag tersebut sudah ditangani di file `app.html`. Silakan dicek kembali.

2023-12-12 14:16 UTC, Farhan-101st commented on src/lib/components/Sidebar.svelte
> +<html lang="en">
![Screenshot 2023-12-12 211231](https://github.com/mdayat/edu-manager-pro/assets/142193896/10f776b6-9822-4610-8153-c6732f5aabd3)
Baik terima kasih untuk proses reviewnya, untuk tag html, head, dan body sudah dihapus sesuai dengan request. setelah dilakukan perubahan, tampilan dari aplikasi website EduManagerPro tetap berjalan dengan normal

2023-12-12 14:45 UTC, mdayat requested changes

2023-12-12 14:45 UTC, mdayat commented on src/lib/components/Sidebar.svelte
> +    <meta charset="UTF-8" />
Karena tag `meta`,`link`, dan `title` adalah bagian dari tag `head`. Seharusnya ketiga tag tersebut dihapus juga.

2023-12-13 00:46 UTC, Farhan-101st commented
![image](https://github.com/mdayat/edu-manager-pro/assets/142193896/0fac79f0-a334-4cb9-95db-4deb753b6375)
baik saat ini aplikasi berjalan dengan baik dengan rincian revisi
1. tag meta, title dan link sudah dihapus
2. menghapus menu schedule dan mengganti dengan menu logout

2023-12-13 06:01 UTC, mdayat commented
> ![image](https://private-user-images.githubusercontent.com/142193896/290040018-0fac79f0-a334-4cb9-95db-4deb753b6375.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NDc1NjgsIm5iZiI6MTcwMjQ0NzI2OCwicGF0aCI6Ii8xNDIxOTM4OTYvMjkwMDQwMDE4LTBmYWM3OWYwLWEzMzQtNGNiOS05NWRiLTRkZWI3NTNiNjM3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwNjAxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2NlZWZjZjE5ODdmMGU4ZDE2NjhlODBlODNhMGFiMTcxNTQzOTI2NThiNzJmNWVmYjNlZmMxZTgzZGU0MTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ClbKb6LHxdPxpuriEpaPBJjXw0GkW9-wlVAJa8nu728) baik saat ini aplikasi berjalan dengan baik dengan rincian revisi
> 
>     1. tag meta, title dan link sudah dihapus
> 
>     2. menghapus menu schedule dan mengganti dengan menu logout

2023-12-13 06:02 UTC, mdayat approved these changes

2023-12-13 06:02 UTC, merged